#include "iFruit.h"

#pragma region Phone Methods

Vector3 UI::Scaleforms::iFruit::getMobilePhonePosition()
{
	Vector3 pos;
	MOBILE::GET_MOBILE_PHONE_POSITION(&pos);
	return pos;
}

Vector3 UI::Scaleforms::iFruit::getMobilePhoneRotation()
{
	Vector3 rot;
	MOBILE::GET_MOBILE_PHONE_ROTATION(&rot, 0);
	return rot;
}

void UI::Scaleforms::iFruit::MovePhone(bool up)
{
	if (up)
	{
		while (getMobilePhonePosition().y < -27)
		{

			MOBILE::SET_MOBILE_PHONE_POSITION(61.5f, getMobilePhonePosition().y + 4, -60.0f);
			Draw();
			WAIT(0);
		}
	}
	else
	{
		while (getMobilePhonePosition().y > -67)
		{
			MOBILE::SET_MOBILE_PHONE_POSITION(61.5f, getMobilePhonePosition().y - 4, -60.0f);
			Draw();
			WAIT(0);
		}
	}
}

#pragma endregion

#pragma region Scaleform Methods

void UI::Scaleforms::iFruit::LoadScaleform()
{
	int start = GAMEPLAY::GET_GAME_TIMER();
	int time = 5000;
	ScaleformMovieHandle = GRAPHICS::REQUEST_SCALEFORM_MOVIE((char*)gfxName.c_str());
	while (!GRAPHICS::HAS_SCALEFORM_MOVIE_LOADED(ScaleformMovieHandle))
	{
		if (GAMEPLAY::GET_GAME_TIMER() > start + time)
		{
			throw std::runtime_error("ERROR: Timed out while loading Scaleform Movie: " + gfxName + ".");
		}
		WAIT(0);
	}

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_SLEEP_MODE");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_BOOL(false);
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_SOFT_KEYS");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(2);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(1);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(2);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(-1);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(-1);
	GRAPHICS::_BEGIN_TEXT_COMPONENT("CELL_205");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_SOFT_KEYS_COLOUR");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(2);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(255);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(50);
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_SOFT_KEYS");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(3);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(1);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(4);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(-1);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(-1);
	GRAPHICS::_BEGIN_TEXT_COMPONENT("CELL_206");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_SOFT_KEYS_COLOUR");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT(3);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(255);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(50);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_THEME");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(5);
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_BACKGROUND_IMAGE");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_DATA_SLOT_EMPTY");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(1);
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_DATA_SLOT");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(1);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(4);
	GRAPHICS::_BEGIN_TEXT_COMPONENT("STRING");
	UI::_ADD_TEXT_COMPONENT_STRING("Email");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("STRING");
	UI::_ADD_TEXT_COMPONENT_STRING("Email");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("STRING");
	UI::_ADD_TEXT_COMPONENT_STRING("Email");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("CELL_217");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("CELL_217");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_DATA_SLOT");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(1);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(1);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(2);
	GRAPHICS::_BEGIN_TEXT_COMPONENT("STRING");
	UI::_ADD_TEXT_COMPONENT_STRING("Messages");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("STRING");
	UI::_ADD_TEXT_COMPONENT_STRING("Messages");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("STRING");
	UI::_ADD_TEXT_COMPONENT_STRING("Messages");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("CELL_217");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("CELL_217");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "SET_DATA_SLOT");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(1);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(2);
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(5);
	GRAPHICS::_BEGIN_TEXT_COMPONENT("STRING");
	UI::_ADD_TEXT_COMPONENT_STRING("Contacts");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("STRING");
	UI::_ADD_TEXT_COMPONENT_STRING("Contacts");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("STRING");
	UI::_ADD_TEXT_COMPONENT_STRING("Contacts");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("CELL_217");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_BEGIN_TEXT_COMPONENT("CELL_217");
	GRAPHICS::_END_TEXT_COMPONENT();
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION(ScaleformMovieHandle, "DISPLAY_VIEW");
	GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(0);
	GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();

	MOBILE::GET_MOBILE_PHONE_RENDER_ID((Any*)&MobilePhoneRT);
	AUDIO::PLAY_SOUND_FRONTEND(-1, "Pull_Out", "Phone_SoundSet_Michael", true);
	MOBILE::CREATE_MOBILE_PHONE(0);
	MOBILE::SET_MOBILE_PHONE_SCALE(280);
	MovePhone(true);
	IsMobilePhoneOpen = true;
}

void UI::Scaleforms::iFruit::Dispose()
{
	if (GRAPHICS::HAS_SCALEFORM_MOVIE_LOADED(ScaleformMovieHandle))
	{
		GRAPHICS::SET_SCALEFORM_MOVIE_AS_NO_LONGER_NEEDED(&ScaleformMovieHandle);
		ScaleformMovieHandle = 0;
	}
}

void UI::Scaleforms::iFruit::Draw()
{
	invoke<Void>(0xE6A9F00D4240B519, ScaleformMovieHandle, true);
	UI::SET_TEXT_RENDER_ID(MobilePhoneRT);
	GRAPHICS::_0x61BB1D9B3A95D802(4);
	GRAPHICS::_0xC6372ECD45D73BCD(true);
	GRAPHICS::DRAW_SCALEFORM_MOVIE(ScaleformMovieHandle, 0.1f, 0.179f, 0.2f, 0.356f, 255, 255, 255, 255, 0);
	UI::SET_TEXT_RENDER_ID(UI::GET_DEFAULT_SCRIPT_RENDERTARGET_RENDER_ID());
}


#pragma endregion

void UI::Scaleforms::iFruit::Control()
{
	if (IsMobilePhoneOpen)
	{
		Draw();
	}

	if (CONTROLS::IS_CONTROL_JUST_PRESSED(0, 172))
	{
		if (!IsMobilePhoneOpen)
		{
			LoadScaleform();
		}
	}

	if (CONTROLS::IS_CONTROL_JUST_PRESSED(0, 177))
	{
		if (IsMobilePhoneOpen)
		{
			MovePhone(false);
			Dispose();
			MOBILE::DESTROY_MOBILE_PHONE();
			IsMobilePhoneOpen = false;
		}
	}
}