#include "RankBar.h"

void UI::Scaleforms::RankBar::Control()
{
	if (!UI::IS_RADAR_HIDDEN() && !UI::IS_RADAR_HIDDEN())
	{
		if (CONTROLS::IS_CONTROL_JUST_PRESSED(0, 20))
		{
			XPStartLimit = CalculateXP(PlayerLevel - 1);
			XPEndLimit = CalculateXP(PlayerLevel);
			GRAPHICS::_REQUEST_HUD_SCALEFORM((int)BarId);
			while (!GRAPHICS::_HAS_HUD_SCALEFORM_LOADED((int)BarId)) WAIT(0);
			SetColor(116, 123);
			GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_FROM_HUD_COMPONENT((int)BarId, "OVERRIDE_ANIMATION_SPEED");
			GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(2000);
			GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();
			GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_FROM_HUD_COMPONENT((int)BarId, "OVERRIDE_ONSCREEN_DURATION");
			GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(6000);
			GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();
			BeforeDraw();
			PreviousXP = CurrentXP;
		}
	}
}

void UI::Scaleforms::RankBar::SetColor(int primaryColor, int secordaryColor)
{
	if (GRAPHICS::_HAS_HUD_SCALEFORM_LOADED((int)BarId))
	{
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_FROM_HUD_COMPONENT((int)BarId, "SET_COLOUR");
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(primaryColor);
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(secordaryColor);
		GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();
	}
}

void UI::Scaleforms::RankBar::StayOnScreen()
{
	if (GRAPHICS::_HAS_HUD_SCALEFORM_LOADED((int)BarId))
	{
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_FROM_HUD_COMPONENT((int)BarId, "STAY_ON_SCREEN");
		GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();
	}
}

void UI::Scaleforms::RankBar::ResetMovie()
{
	if (GRAPHICS::_HAS_HUD_SCALEFORM_LOADED((int)BarId))
	{
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_FROM_HUD_COMPONENT((int)BarId, "RESET_MOVIE");
		GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();
	}
}

void UI::Scaleforms::RankBar::SetRankScores(int xpStartLimit, int xpEndLimit, int previousXP, int currentXP, int playerLevel, int rankNext)
{
	if (GRAPHICS::_HAS_HUD_SCALEFORM_LOADED((int)BarId))
	{
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_FROM_HUD_COMPONENT((int)BarId, "SET_RANK_SCORES");
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(xpStartLimit);
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(xpEndLimit);
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(previousXP);
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(currentXP);
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(playerLevel);
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(100);
		GRAPHICS::_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT(rankNext);
		GRAPHICS::_POP_SCALEFORM_MOVIE_FUNCTION();
	}
}